### ISSUE TITLE
Add PT Shadows over Innistrad results

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#1]
@czarandy I could help out/contribute here. Any insights on how you crawled the initial data?

**Comment by czarandy** [comment]
I had a hacky Python script that parsed the wizards site html, but they keep changing the format so it stopped working. The newest version of their site uses JS so you can't even load all the results at once.

**Comment by mlnmln** [comment]
Alright. I'm in the process of hacking something new on top of https://github.com/redco/goose-parser . Made progress by blacklisting the JavaScript responsible for the data tables, so at least I get all results now. I'm currently working on transforming the data to match your format. Could give you access if you are interested.

**Comment by czarandy** [comment]
Thanks for adding this!

**Comment by mlnmln** [comment]
Cool. Would you update the github pages branch then?
