### ISSUE TITLE
Standings at Team Pro Tours

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#105]
Somehow the players at team Pro Tours are ranked 1,2,3,4,... now instead of 1,1,1,2,2,2,3,3,3,... or in the case of San Diego 1,1,2,2,3,3,...

**Comment by czarandy** [comment]
Ah, sorry. This is fixed in https://github.com/czarandy/mtgptresults/commit/4f0632fe98463d0be444f5b070805fa143577fbb
