### ISSUE TITLE
Commits to master

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#120]
Hi Andy, I think I just inadvertently committed a few of my updates to your master branch (I hadn't thought that was even possible). I don't think I added something damaging, but still apologies, I didn't mean to meddle with your branch.

There should be nothing to act upon here (I think). It's just to make sure that you have seen this. Please archive after you have seen this.

**Comment by czarandy** [comment]
Yeah you can do it because I gave you push access. So it's not unexpected.
