### ISSUE TITLE
PT Hour of Devastation

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#121]
Can one of you please parse and upload the latest PT?

**Comment by quick-mtgstat** [comment]
I don't really have stuff well set up for git on my computer with my mtg stuff, but I did a parsing of PTHOU in a form that I think matches the json form you guys have been using here. Figured I'd upload it even if I didn't want to try to connect more sensibly and push it.

[pro-tour-hour-of-devestation-2017.json.txt](https://github.com/czarandy/mtgptresults/files/1268806/pro-tour-hour-of-devestation-2017.json.txt)

**Comment by czarandy** [comment]
Thanks for the data. I've updated it now.

**Comment by OdinFK** [comment]
Sorry to reopen this, but could you parse the PT HOU file for new players and put them into the players.json. Makes life so much easier for me :)

Also was there a way I can do that easily myself? If so I don't remember, but if you give me a hint I will try not to bother you with this the next time...

**Comment by czarandy** [comment]
Oops, forgot to do that. All you have to do is run 'grunt metadata'. I've updated it now.
