### ISSUE TITLE
Navigation from main to PT page

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#125]
There is a somewhat weird "problem" that when you click on a Pro Tour on the main page, you are directed to the page of that Pro Tour, but you do not necessarily land at the top of that page. What I believe happens is that somehow the website keeps track of what line you were looking at on the frontpage and does not reset that (or even keeps track of this), and then tries to show you the same line on the page of the Pro Tour.

It is a weird and just a little annoyance, but if you happen to know where it comes from and can clean it up easily it would be appreciated.

**Comment by czarandy** [comment]
Thanks, I fixed this in https://github.com/czarandy/mtgptresults/commit/1b88ec1f0165f38a75da4c1a6d696ef11267ff40
