### ISSUE TITLE
Team size denominator

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#130]
Currently team sizes are "calculated" by querying the variables `team` and `team2hg`. However, this only allows for two- and three-player teams. Other tournaments used 4-player teams (Worlds), and 5-player teams (Atlanta).

Going forward it would make more sense in my opinion to replace the aforementioned varibales by one called `teamsize`. If the variable is set team size is the integer given in the variable and otherwise it is assumed to have been an individual competiton. Can you accomodate that in the code?

**Comment by czarandy** [comment]
Good idea. I've changed it to just have a `teamsize` for team tournament in https://github.com/czarandy/mtgptresults/commit/f648e79c782d74824922bc252e9cc8effebd1b2d
