### ISSUE TITLE
Some players' T8/Total is 0%

### ISSUE THREAD

**Issue by MarianoMolina** [czarandy/mtgptresults#132]
Found several instances:

David Mills
Ervin Tormos
Luis Salvatto

And there are others. This is in: http://www.mtgptresults.com/rankings/t8

And they obviously have some ammount of Top 8 so should be non-zero.

**Comment by OdinFK** [comment]
Thank you very much for pointing it out. I will take a look at it tomorrow and try to find out about the systematic behind the error.

Andrew Brown is also 0%

**Comment by czarandy** [comment]
It looks we only include the T8% if you've played in >= 10 PTs, to avoid the rankings being dominated by someone that T8ed their only PT.

**Comment by czarandy** [comment]
We should change it to show something else instead.

**Comment by czarandy** [comment]
Ok I made it more explicitly say "too few PTs" if it's <10.
