### ISSUE TITLE
Logos for various event types

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#140]
Not sure how and where to include these myself, but as of now the images for some of the new event types are inappropriate. Better images would be:

Magic Online Championship:
http://archive.wizards.com/mtg/images/digital/magiconline/logo_magiconlinechampionship.png

Magic Invitational:
There doesn't seem to be an official logo. The standard Magic logo should do:
https://www.forbiddenpower.com/wp-content/uploads/2016/08/Mtg-logo-700x560.png

The Duelist Team Challenge:
It is only one event. I think the standard Magic logo would do well once again.

**Comment by OdinFK** [comment]
This would be an adequate icon for the World Magic Cup (the are a few in the backlog):
https://d1u5p3l4wpay3k.cloudfront.net/mtgsalvation_gamepedia/7/70/Magic_Cup.jpg?version=d8496fa9f031e144c79caa19be1294b5

**Comment by mtgmagicalhack** [comment]
@OdinFK I believe you should be able to update the logos yourself. Images need be placed in `/data/logo` and are referenced in the json files by their files name only. 

```
"logo": "ptdom.png",
```

Size is roughly

**Comment by OdinFK** [comment]
I think I managed to add logos for the other events. We still miss a few more adequate logos, but I think we can close this issue for now anyway.
