### ISSUE TITLE
Pro Tour Dominaria

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#142]
Please add this to the website.

Also currently some players have no entry in the players.json. Would be cool if you could correct that at the same time.

**Comment by mtgmagicalhack** [comment]
@czarandy I created a PR for ptdom, took a bit longer, needed to update the parser as the HTML on the standings page had changed again. 

@OdinFK Please create a separate issue for the missing the players, I don't know wich players are affected.
