### ISSUE TITLE
Players missing in players.json

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#144]
Previously the players.json was automatically updated with new players whenever a new file was added to our database. However, the new 'other events' have not been added to the database yet although the data is online by now.

I could of course do this manually, but this is not only work, that doesn't really need to be done. Doing this automatically is actually quite useful for me. All the new players were always automatically be added at the end of the players.json and afterwards it makes it very easy for me to look for duplicate entries and misspelled players.

**Comment by czarandy** [comment]
I updated the players.json file

**Comment by czarandy** [comment]
https://github.com/czarandy/mtgptresults/commit/5a9263d85166fed2016cfc8d833a6a1716931077
