### ISSUE TITLE
Top 8/16 calculation faulty

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#147]
-Shahar Shenar is displayed as having zero Top 16 finishes although he finished PT Ixalan in 14th place which i correctly displayed.
-Seth Manfield is displayed as having 1 win and 3 Top 8s, but he has the win + three top 8s, which is four Top 8s. I checked other players, number of Top 8s is otherwise correctly calculated by including the wins.

I have no clue why these numbers are not calculated correctly, though.

**Comment by czarandy** [comment]
Looks like it was because PT Ixalan was missing the teamsize argument. Fixed in https://github.com/czarandy/mtgptresults/commit/d3cc74255fdc6ea3d58b4624f9b2e2d73eb5b73f
