### ISSUE TITLE
About various things I'd like to do

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#15]
Hey,

after the latest fix to the tournaments.json the database should be in pretty good shape, at least basically as good as it gets without help from the concerned people. That means that the site is pretty much finished in the current scope of the project.

I would love to do further things, but I don't know what your ideas for this site were, Andy. Also I'm mostly incompetent when it comes to writing code, so while I can find and manage all the data I will not be able to make them visible or increase the functionality of the site.

So what's next? What are your ideas for this?

(I am aware that this is probably not the optimal place for such a discussion, but for now it is the easiest way to get in touch with you)

Edit: Just noticed that this doesn't quite do justice to the title. So a few examples, in the post after yours, Andy

**Comment by czarandy** [comment]
I really wanted to include GP results, but there are so many more of them I don't see myself having the time to do it. But that would be a really cool thing to have. 

Do you have any ideas?

**Comment by OdinFK** [comment]
GPs would indeed be super cool. That was my first inclination, too, and then I updated those PT players. Now I think it is basically impossible to have a somewhat clean database for that, so I thought more of ways to go deeper on the PT related stuff.

*I think it would be cool to link coverages, and where possible the original coverage, not the garbage that Wizards made out of them. Similarly I think it would be cool to link tournament reports. There is a lot of stuff in the webarchives, that is super-tedious to access individually, but would be a good fit this.

*On the data side I think a playerdata file would be useful. Information about the players, that is not or only extremely rarely changing could go there. Nationality, Hall of Fame, nickname if very prominent, Pro Player of the Year titles, the native spelling of the player's name, Natonal titles, etc (these things don't all have the same priority) For the PTs themselves I would like to have an option to create associated events. PTs have often been held in conjunction with events, that were basically a part of the PT (Worlds Teams, Masters Series, Junior Division, other Divisons pre-98)

*On the front end side, it would be cool if on the player sites clicking on Wins/T8/T16/$ gave you a list of the most successful players based on that stat. On the PT sites total player count, number of swiss rounds, and cash awarded could be included, although not that important.

*Decks! I have tried to look up old decklists from PTs, but I have no real place to put my findings. At least Top 8 Decklists would be a great fit I think.


If I understand this .json data format correctly I could just add most of the stuff to the files, and you use it whenever you have the time to work on the site, correct? I mean a line like
coverage = "http://www.wizards.com/...", will not do any harm. In the worst case it is unused, correct?

**Comment by czarandy** [comment]
Yeah, I wanted to have a "top ranking" thing. Especially around HOF voting season it seems like a popular discussion topic. The downside is without GP stats you are kind of missing a big part of it.

Yes, you can add extra data and it will be ignored. It will increase the size of the data we send, but that's probably not significant unless you are adding huge amounts.

**Comment by OdinFK** [comment]
>Yeah, I wanted to have a "top ranking" thing. Especially around HOF voting season it seems like a popular discussion topic. The downside is without GP stats you are kind of missing a big part of it.

I agree that having GPs would be great, and all the Pro Points look wrong without them. Of course we could just do it, but there are quite a few things to consider
*The amount of data will grow about tenfold, this will impact the site for the user I suppose
*For players like Shuhei Nakamura his personal site will look very cluttered with ~200 events instead of ~50
*Early GP standings are incorrect, hard to crawl, and/or incomplete.
*There will be an immense amount of persons, that appear under multiple names, and we will usually have no way of correct that
*We will have players with identical names (actually we already have two Daniel Gardners)

These problems could be mitigated if there was a way for the user to select if they want to display GP stuff at all. I suppose the easiest way would be to have checkboxes that decide whether Pro Tour, Grand Prix, Other events are displayed.

Concretely I wonder how I would go about adding new events. mlnmln suggested splitting the tournaments.json into individual tournament files. Another way to go might be to have three files (PT, GP, other). And finally of course it would be possible to just lump everything together. Either way I can add new data right now, but I would need to know which way we are going.

**Comment by czarandy** [comment]
I agree we'd have to change the way we display data if we actually have all the GPs, because, as you say, it will be ~10x the data size. One idea I had was to only include GP results that get any pro points. That should greatly reduce the size of data.

**Comment by OdinFK** [comment]
I like this idea. It sucks that we cannot display how many GPs a player has played, but it solves most of the other problems relatively well.

**Comment by mlnmln** [comment]
@czarandy @OdinFK 

I'm going to hijack this issue as well, bear with me. 

* I would like to see to that this project gets some traction. 
* I'm an experienced frontend developer with a design and mtg background. 
* I brought this project to @OdinFK attention as he seems to be a natural fit. 

As for future development here is what i can offer: 

* I should be able to develop _small to medium_ new features on my own. 
* I am an expert CSS author, specialized in creating responsive experiences. 
* I am proficient in JavaScript and should be able to handle most of the view logic. 
* I could do onboarding of new members and write docs. 

Limitations: 
* I do have a full-time job, can realistically offer max 2-4h/week. 
* I might need some advice/help regarding data structures from @czarandy 

Features: 
* I think most new feature requests should come from an editor's perspective, namely @OdinFK 
* I could craft an identity for the site that goes beyond bootstrap. 
* I would like to see win percentages of a certain certain player. Means that we would need number of rounds for each pt. 

Licence: 
* I expect this project to be public and MIT for the foreseeable future. 
* I don't expect anything in return, except a contribution note in the readme.

**Comment by czarandy** [comment]
I'm happy with all of that. Any improvements you want to make are definitely appreciated and I can probably help to some extent depending on how much free time I have.

**Comment by mlnmln** [comment]
> I'm happy with all of that. Any improvements you want to make are definitely appreciated and I can probably help to some extent depending on how much free time I have.

Awesome. 

I think we should split the remaining feature requests from @OdinFK and me into separate issues and close this one. That way we can determine their priorities better and won't have one large "thread" that gets never closed.

**Comment by OdinFK** [comment]
> I think we should split the remaining feature requests from @OdinFK and me into separate issues and close this one. That way we can determine their priorities better and won't have one large "thread" that gets never closed.

Yes, that makes sense.

I think the first feature, that should be implemented is having best player lists in various categories. Clicking on Winners in the player overview should yield a list of players sorted by how many PTs they won. Same for top 8 (probably only having players with at least 2 top 8). Same can be done for T16, participations, cash won, and Pro Points. I believe these features should be relatively straightforward and quick to implement, but maybe there is a pitfall, that I don't see as a non-programmer.

The other thing is, you mention win%. That would be *AWESOME*, but it is also very hard. There are many PTs for which we don't have the scores and even for the newer ones it would be necessary to know how many rounds a player played. They might not have made a cut, or dropped. Do we count Top 8? How do we get all the scores into the files? Is a draw 33% win or 0%? And then there are some super-arbitrary things like the Pro Tours, where we know they used a different system to determine the score. (in the beginning each round was three games no matter what, and the number of games won was your score). Also it would in theory be preferable to have the actual record instead of the score. For a time they listed the record, too, but nowadays it is back to only points. I put a lot of effort into my personal data files to have some background on how players performed (for my interviews, and the occasional statistics article) but even I was not crazy enough to go for the win percentages...

**Comment by mlnmln** [comment]
@OdinFK I created individual issues for each topic. That way we can better track progress, I think I got everything and this issue could be closed now. If i missed anything, feel free to open additional issues.
