### ISSUE TITLE
parse pt 25tha data

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#154]
I just uploaded the Silver Showcase. Would be sweet if you could parse the PT results when it's done later tonight (should be in 2-3 hourse), and also update the players.json. I will care for the rest then tomorrow or the day after.

Thanks!

**Comment by OdinFK** [comment]
The next PT is coming up and this is still not online :-/
Are you guys not interesting in pursuing this project any further?

**Comment by OdinFK** [comment]
It would be awesome if you could parse PT25 and PT GRN.

**Comment by czarandy** [comment]
I added those PTs finally. Unfortunately the team one they only have last names in the standings table so it makes it not ideal :(
