### ISSUE TITLE
How to deal with umlauts/special characters in player names?

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#2]
@czarandy 

Given

http://www.mtgptresults.com/player/daniel-grafensteiner

vs. 

http://www.mtgptresults.com/player/daniel-gr-fensteiner

Which one should be the correct one? I assume the latter. 

Is there a way in react-router to beautify their respective urls? 

E.g.: 

http://www.mtgptresults.com/player/daniel-graefensteiner

**Comment by czarandy** [comment]
I usually use the latest version from Wizards, so I would actually use the former. But it's kind of arbitrary. Right now you have to just rename all the references in the json files to get the urls to change; I don't have it set up to allow aliases or anything.

**Comment by mlnmln** [comment]
> I usually use the latest version from Wizards, so I would actually use the former

I think this should probably go into the readme or the project's wiki to have a guideline for future contributors. What do you think?

**Comment by czarandy** [comment]
Yeah, although I'm not completely sure about it, since it seems like some of the recent names aren't really better (maybe they are just dropping the accents for no reason?)

**Comment by mlnmln** [comment]
> Yeah, although I'm not completely sure about it, since it seems like some of the recent names aren't really better (maybe they are just dropping the accents for no reason?)

Agreed. We should probably not rely on the assumption that wizard's newest standings are the most correct ones. 

@OdinFK 
What do you think? Under which rule should we do names and urls of players with special characters in their name?

**Comment by OdinFK** [comment]
I would do it like this

For all players that come from countries, that use the Latin alphabet
*spell the name in the native way
*in the url replace all special characters with - (that's how it is done atm)
*configure the search field in a way that it accepts the base characters instead of the special character (entering martin juza should display martin jůza)

For Japanese/Russian players
*spell the name in the most common latinized version
*have the original native on the player's site

**Comment by mlnmln** [comment]
> I would do it like this

> For all players that come from countries, that use the Latin alphabet
> * spell the name in the native way

+1 

> * in the url replace all special characters with - (that's how it is done atm)

I think, having url of http://www.mtgptresults.com/player/rapha-l-l-vy would be better thant http://www.mtgptresults.com/player/rapha-l-l-vy as it now. However the links are out there and we would need a migration strategy to not break them. I'm fine with sticking to the current pattern. 

> * configure the search field in a way that it accepts the base characters instead of the special character (entering martin juza should display martin jůza)

+1 

> For Japanese/Russian players
> * spell the name in the most common latinized version
> * have the original native on the player's site

This seems fine, but would lead to some additional meta data for the players.

**Comment by OdinFK** [comment]
What's the difference between the spellings of raph levy? They seem to be the same.

**Comment by mlnmln** [comment]
> What's the difference between the spellings of raph levy? They seem to be the same.

Copy + paste error. :)

Should be http://www.mtgptresults.com/player/raphael-levy which is more human-readable.

**Comment by OdinFK** [comment]
Sure, I agree that this is better. Is there a way to convert this stuff without tons of additional work?

**Comment by czarandy** [comment]
It should be possible to convert automatically using something like this:
https://github.com/FGRibreau/node-unidecode
One option would be to drop the explicit ids from tournaments.json, and
have them auto generated based on the names.

**Comment by OdinFK** [comment]
I've just been made aware, that there are two different Paulo Carvalho. Fortunately one seems to be from Brazil and one from Portugal, so I can find out who is who. How do we want to deal with this? Here? In the future? (affects how conversions need to be done if you want to do them automatically)

**Comment by czarandy** [comment]
Yeah that's a potential problem. We could list them as Name (Country) for
such cases. Hopefully we don't have two people with the same name from the
same country :)

**Comment by mlnmln** [comment]
See #24.
