### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#20]
I registered a Twitter account for mtgptresults. I hope this is okay with you. For the last couple of updates I have tweeted them from my Twitter account, but I'd prefer it if there is a Twitter account for this.

The motivation for a Twitter account is twofold in my opinion
*people can follow it and be aware of udpates to the site
*if this site becomes more popular (as it should be) then people can tweet links to their reports to @mtgptresults and this it would be way less tedious to get the tournament reports linked

In both cases the gains might not be phenomenal, but the cost is low, too. Just in case, if ownership of the Twitter account is an issue, I can certainly register it to an email account made for this purpose, and give you the password.

**Comment by czarandy** [comment]
Sure, if you want to manage the twitter stuff :).

**Comment by mlnmln** [comment]
Seams great! 

If people comment on wrong data, I would recommend letting them raise an issue here or doing it yourself. That way we have actionable small issues and won't miss anything by accident.

**Comment by OdinFK** [comment]
I'll look into that tomorrow. I use Twitter frequently, but I have absolutely no clue about shared accounts, either. It's a thing that usually just does not come up.

**Comment by OdinFK** [comment]
I didn't know Tweetdeck before. This seems to be the advanced user interface for Twitter. It wastes much less space than normal Twitter, so it way probably a 'good to know' thing anyway.

Tweetdeck has the functionality we were searching for indeed. I have given both of you contributor rights. Can you please check that I granted rights to the correct persons aka your accounts? I will grant you admin rights then. I don't think it makes much of difference, but no need for me to be the allmighty admin alone...

When you go to https://tweetdeck.twitter.com/ while being logged in on Twitter you should immediately see how this works.

**Comment by czarandy** [comment]
Thanks, it's the right account for me. Looks like it's working.

**Comment by mlnmln** [comment]
Works perfectly, thanks!
