### ISSUE TITLE
Add different tournament types

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#23]
There are quite a few things to do still, but we do want to have other PT related tournaments at some point, right? How do we want to distinguish the different tournaments? Do we put a marker in each tournament file that goes like `"type": "pt"` and do according things for other tournament forms? I ask because if we do not distinguish and we add other forms of tournaments, then the Top 8 count etc will invariably incorrect.

**Comment by czarandy** [comment]
Good idea. We can probably just use subdirs for this, e.g. data/pt for PTs, data/gp for GPs, etc.
I can change the build script to add the type. 

Are you planning on adding another type of tournament? I'd rather wait till we have some other data to add before doing these changes :).

**Comment by OdinFK** [comment]
Primarily I would like to have the WMCs/Worlds team competitions and the modern Worlds in there.

As a kind of personal obsession, I would like to add the other events that were associated to the PTs (Junior Division and that kind of stuff). It is not all that important obviously, but on the other hand not even Wizards has that on their website, so it is kind of showing off, that we are going a deeper.

Technically doing associated events should be easy, all it needs is one link after all. On the other hand before we do team competitions we should decide on how to manage national teams. Treating them like players would go some way, but having an additional data type, that has a team-id, team-name, and an array of associated players might be preferable.

Doing the Modern Worlds is trivial I suppose.

**Comment by mtgmagicalhack** [comment]
@OdinFK This duplicates #38, doesn't it?

**Comment by OdinFK** [comment]
Not quite, but they are probably close enough to not warrant two issues.

-Associated events was about having a parent/child relationship between Pro Tours and associated events like junior pts or worlds team competitions
-Add different tournament types is about assigning specific tournament types. I can do this "without your consent" but just doing it and not telling anybody leads nowhere so I added an issue. This one is actually becoming more important as we are adding non-PT events to the website. As far as I am concerned PTs should be tagged Pro Tour and then you can easily only put PTs on the landing site, and all other events in the to-be-created other events section.

**Comment by mtgmagicalhack** [comment]
@OdinFK This can be closed now, right?
