### ISSUE TITLE
Worlds can't be read completely in the search suggestions

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#26]
Currently the Worlds are named 'World Championships (xxxx)'. The problem is that there are too many Worlds for them to all be displayed in the search field. If it was 'xxxx World Championship' (the American naming convention afaik) then this results in a more convenient way to find specific Worlds.

Just a very minor thing obv, but I think it thus makes sense to rename these tournaments (don't know if it is necessary to rename the files, too)

**Comment by czarandy** [comment]
It's a good idea. Right now the search box just does Name (Year) for all tournaments. We would need some way to know that for worlds we want Year Name but for other PTs we still want Name (Year). Hmm

**Comment by mlnmln** [comment]
A quick fix would be if just made the search box wider. 
That way we don't have to make any exceptions for worlds.

**Comment by czarandy** [comment]
Sure
