### ISSUE TITLE
Use pre commit hooks to run json lint

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#31]
@czarandy 

We should not have non-valid JSON in our repo. What do you think of using st like https://www.npmjs.com/package/grunt-githooks or https://github.com/observing/pre-commit check if our JSON is valid before committing?

**Comment by czarandy** [comment]
Sure, can't hurt. Added a hook to run jshint and jsonlint:
https://github.com/czarandy/mtgptresults/commit/5d77d9fd80de1c3083c5a3d1705726f8995944b0
