### ISSUE TITLE
Search function broken

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#33]
The search is not working for me right now. I also saw that I did not enter a name for the 96th place finisher. Not sure if these things could be related, but I pushed a correction. Maybe see first if this mistake indeed broke it.

**Comment by mlnmln** [comment]
@OdinFK 

this is likely an error in our JSON files. 
JSON is very strict about commas, quotes etc, ...

We recently added a tool that checks if our JSON is valid. 

In your console run 

```
npm install 
```

then 

```
grunt json
```

which should tell you any errors in our JSON files. 

With our recent git hook update, The check should happen automatically before any commit.

**Comment by OdinFK** [comment]
I already check all the files with jsonlint, because I made errors in one file previously and Andrey advised me to do that.

The files are correct, however in the NY98 file the last entry currently is this

        {
            "id": "Hannes Kaplan",
            "name": "",
            "propoints": 3
        }

Json is fine with it, but my conjecture at this point is, that having a no-name breaks the search function.

**Comment by czarandy** [comment]
Yes, because of a quirk of the typeahead code, having a name that is empty string breaks it completely :(.

**Comment by czarandy** [comment]
I pushed your latest change that fixes the empty name, so it is fixed now.

I think the right way to fix this is https://github.com/czarandy/mtgptresults/issues/24. If we autogenerate ids we can have that part fail if the name is empty string or invalid in some other way.
