### ISSUE TITLE
Add links to coverage

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#36]
> *I think it would be cool to link coverages, and where possible the original coverage, not the garbage that Wizards made out of them. Similarly I think it would be cool to link tournament reports. There is a lot of stuff in the webarchives, that is super-tedious to access individually, but would be a good fit this. 

#15

**Comment by OdinFK** [comment]
Andy already took care of that, and I provided the links. Every PT that ever had a coverage has its coverage linked :)

**Comment by mlnmln** [comment]
Alright, didn't know. Will close. :)
