### ISSUE TITLE
Add player meta data

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#37]
> *On the data side I think a playerdata file would be useful. Information about the players, that is not or only extremely rarely changing could go there. Nationality, Hall of Fame, nickname if very prominent, Pro Player of the Year titles, the native spelling of the player's name, Natonal titles, etc (these things don't all have the same priority)

#15

**Comment by OdinFK** [comment]
I would wait with this until I have finished adding all the NY98 players. A few new ones might be in there. Then a player metadata file should be generated from the tournament data files. When this is done all the names should be removed from the individual tournament files, too. This is information that should go into the metadata.

Havin Hall of Fame tags is something that I consider relatively important. The HoF votings are going to be held in about a month, and if we had HoF tags and top lists by then, then we would have a very valuable website for the Hall of Fame voters I believe.

This will become high priority in about a week I think.

**Comment by czarandy** [comment]
Sounds pretty cool. What kind of lists do you want to have?

**Comment by OdinFK** [comment]
The very basic things would be Wins / Top 8s / Top 16s. In articles they sometimes also refer to T32/T64. However, money finishes might be more interesting than just continuing down the TX, T(X*2), T(X*4) lane.

Pro Points would fill an interesting hole. You can find the total Pro Points easily on the Wizards page of course, but we only have the Pro Points from the Pro Tour right now and that might fill a hole as Pro Tour Pro Points are a more valuable metric for the Hall of Fame in a way.

If you also want to have some stats that are relative to the number of attendances, then I would suggest attendances/Top8s

Of course there are a bunch of other things one could do like medians or avg Pro Points / attendance, but most of them are rather meaningless considering how drastically the Pro Tour has changed since the early days.

**Comment by czarandy** [comment]
That sounds like #39 will take care of it for the lists. So this is more about including other metadata about players. We can then include it on the player page. We could also include tags in lists like [HOF] [PT Top 8] [PT Winner] etc.
That would be nice when scanning lists so you could see how "stacked" a top 8 is for instance :)

**Comment by mlnmln** [comment]
> We could also include tags in lists like [HOF] [PT Top 8] [PT Winner] etc.
That would be nice when scanning lists so you could see how "stacked" a top 8 is for instance :)

I like this idea in particular! 

@czarandy How do we progress here?

**Comment by OdinFK** [comment]
I would just color-code the lines with Hall of Famers. Having a bunch of tags will probably make it look cluttered, but I would not want to stop you. Try it by all means. If we don't like it it can be changed.

**Comment by czarandy** [comment]
I'll work on a basic version of this (HoF for now)

**Comment by mlnmln** [comment]
> I would just color-code the lines with Hall of Famers. Having a bunch of tags will probably make it look cluttered, but I would not want to stop you. Try it by all means. If we don't like it it can be changed.

I'm going figure st out that doesn't clutter the standings too much.

**Comment by OdinFK** [comment]
I did a final pass over all PTs. Again I fixed a few hundred entries. I don't think there is much incorrect data left, at least not much, that we will find on our own. Therefore I think this would be a very good time to create a player metadata file from the tournament files.

I don't know how you envisioned doing this, but my idea would be to have a playermetadata.json file, and a script, that adds data from individual tournaments to the playermetadata.json file. In the best case it does this alphabetically and returns the names that it actually added (existing names should not be added of course).

**Comment by czarandy** [comment]
I'll try to get this done soon

**Comment by czarandy** [comment]
Ok so I made a basic version of this. There is a 'players.json' file. It gets filled in with players from all the tournaments listed. You can run 'grunt metadata' to have it update the file and it will print out any names that were added/removed. So this is an easy way to check when adding a new tournament whether the names make sense. Separately you can edit the file and add any metadata. I added some "hof" tags as an example. This part doesn't do anything yet.

https://github.com/czarandy/mtgptresults/blob/master/data/players.json

**Comment by OdinFK** [comment]
Looks good. Can we close this issue now?
