### ISSUE TITLE
Add associated events

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#38]
> For the PTs themselves I would like to have an option to create associated events. PTs have often been held in conjunction with events, that were basically a part of the PT (Worlds Teams, Masters Series, Junior Division, other Divisons pre-98)
#15

**Comment by OdinFK** [comment]
I consider this a medium priority right now. Having Worlds team competitions would be awesome, but we need to have a data structure and possibly even display "technology" to allow for teams. In the team PTs this part was skipped by just not using team names (which makes sense to me, given how janky most of them are), but countries are a different story. Would be cool to click on Wales and see in which tourney they participated and how they did.

Maybe just change the name to *MEDIUM* Add associated events?

**Comment by mlnmln** [comment]
> Maybe just change the name to MEDIUM Add associated events?
We do have labels for issues, but only Andrey can set them I think.

**Comment by OdinFK** [comment]
I think I have an easy solution for this. Could we have a rider "Associated Events" next to "Player Rankings" on the main page? Clicking on this would lead to a page which is built like the main page, only that it shows all non-PT events. This should be very simple to implement, right?

Would be cool if one of you could do this for me. I have found final standings for most Junior PTs, and some of the other divisions (as they called them back then). The new worlds could also go there.

For the individual player view I imagine that the page is created as is, and if the player participated in any non-PT events there will be a rather fat horizontal line after the PTs, and after this the other events will be displayed. (they will not be used to calculate any stats, though)

Could one of you do this for me? As I understand it this should be really simple and fast to implement and would give the site some cool unique information, that cannot be found anywhere else on the internet.

**Comment by czarandy** [comment]
If you send the data then I can try to do this when I get some free time. You could just commit it into a new file in this repo somewhere (I can modify the format later).

**Comment by OdinFK** [comment]
I have created files for every top-level/invite only tournament, that I could think of. This includes
-old Worlds
-new Worlds
-Junior Pro Tours
-Associated Pro Tour divisions (Classic & Teams)
-Invitationals

I think that is basically everything you could add other than the MOCS finals. Do we want that? Wouldn't be too much work.

If you want to work with this stuff, I have uploaded the files here:
https://drive.google.com/open?id=1lA0aS8ECBC2LuX-cOuvMBIGwDMGHzMQ7

**Comment by OdinFK** [comment]
I have added the MOCSes to the aforementioned directory. There is everything online now, that I think qualifies as a top tier Magic tournament. Not in all cases the data is complete, but I think it would be very worthwhile to add an 'other tournaments' section now.

As a first step you could ignore the way the player view is constructed and just add the other tournaments to its own section. Should be mostly copy/paste from the current events constructor.

**Comment by OdinFK** [comment]
I've added the first five Masters. Somehow I forgot about those. I also found another Team Challenge from PT3. Including the missing events we will have 50 (!) new events on the site.

**Comment by OdinFK** [comment]
The aforementioned 50 events are all complete:
https://drive.google.com/open?id=1lA0aS8ECBC2LuX-cOuvMBIGwDMGHzMQ7   (same as above)

**Comment by mtgmagicalhack** [comment]
@OdinFK This is awesome! I will work in this with high priority. cc @czarandy

**Comment by OdinFK** [comment]
In case you just downloaded the data. I uploaded a few World Team Competitions. This is an ongoing project, but it takes a while to add these.

**Comment by mtgmagicalhack** [comment]
#138

**Comment by OdinFK** [comment]
I added some more events. All the Worlds Team Competitions are in /the directory/ now.

Do you guys have an easy way to parse the data from the World Magic Cups? I did the first one manually (it was not on the Wizards site anyway), but I am not actually craving the idea to do another five manually.

**Comment by mtgmagicalhack** [comment]
> Do you guys have an easy way to parse the data from the World Magic Cups? I did the first one manually (it was not on the Wizards site anyway), but I am not actually craving the idea to do another five manually.

Currently not, no. 

Please open a new issue for adding the other world magic cups. Otherwise issues in our tracker never get closed.
