### ISSUE TITLE
Add players page with top rankings

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#39]
> *On the front end side, it would be cool if on the player sites clicking on Wins/T8/T16/$ gave you a list of the most successful players based on that stat. On the PT sites total player count, number of swiss rounds, and cash awarded could be included, although not that important.

#15

**Comment by mlnmln** [comment]
>  think the first feature, that should be implemented is having best player lists in various categories. Clicking on Winners in the player overview should yield a list of players sorted by how many PTs they won. Same for top 8 (probably only having players with at least 2 top 8). Same can be done for T16, participations, cash won, and Pro Points. I believe these features should be relatively straightforward and quick to implement, but maybe there is a pitfall, that I don't see as a non-programmer.

#15

**Comment by mlnmln** [comment]
@OdinFK @czarandy 
I agree that this should be one of our highest priorities. Effort/Result ratio seems good to me.

**Comment by czarandy** [comment]
I'll work on this. I'll make a "Players" page that will let you sort by the different columns so you can see the top by each metric.

**Comment by czarandy** [comment]
Ok, I have done. For some reason github isn't updating though, so I'm going to wait a bit to see if it fixes itself :/

**Comment by czarandy** [comment]
Ok looks like it updated. http://www.mtgptresults.com/rankings/total

**Comment by mlnmln** [comment]
This is great work, thanks! 🎉 

I would would like to add some minor points: 

* The default ranking should be either Wins or Top 8s, as these are major criteria of success. 
* We have a slight jump in the column width as the sorting icon gets added and removed. 
* Numbers should be right-aligned so it is easier to compare digits. 
* At mobile we could have a fixed table header and first column, also the labels could be shortened. 

I could do these optimisations mid- to end-of-week, as I'm currently down with the flu.

**Comment by OdinFK** [comment]
Totally awesome!!

I think Top 8s is the best ranking, because this is generally accepted as the ranking of greatness in Magic. I would really like one relative ranking as all the currently ranked stats improve with the numbers of attendances. Attendances / Top 8 for all players with at least 10 attendances would be great I think.

**Comment by czarandy** [comment]
Ok I switched it to default to top 8. I'll leave the style tweaks to you @mlnmln 

I also added top 8/total for players with >= 10. I don't know if this is the best "non strictly increasing" ranking, but I guess it's fine. Something like T64/total might be a better indication of "consistency" if that's what we're looking to capture.
