### ISSUE TITLE
Develop page load strategy 

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#41]
> I agree we'd have to change the way we display data if we actually have all the GPs, because, as you say, it will be ~10x the data size. One idea I had was to only include GP results that get any pro points. That should greatly reduce the size of data.

#15

**Comment by mlnmln** [comment]
@czarandy 
Given that we currently expose all data to the client, we could develop a strategy to only load the needed data for a particular route. Some kind of fake API like /:player-id/ /:pt-id/ etc, ... 

Needs some thinking, but if we plan on adding a lot more data, we should plan accordingly. 
Also having an API for 3rd party developers would be AWESOME. Currently probably out of scope.

**Comment by czarandy** [comment]
I kind of wanted to keep it simple and just have a static site. 

Currently for the API you could just load the JS data files directly :).

**Comment by mlnmln** [comment]
I do agree that this is out of scope for now. 
Let's close it and think about it, when it becomes an actual need, not an hypothetical one.
