### ISSUE TITLE
Add win percentages

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#42]
> The other thing is, you mention win%. That would be AWESOME, but it is also very hard. There are many PTs for which we don't have the scores and even for the newer ones it would be necessary to know how many rounds a player played. They might not have made a cut, or dropped. Do we count Top 8? How do we get all the scores into the files? Is a draw 33% win or 0%? And then there are some super-arbitrary things like the Pro Tours, where we know they used a different system to determine the score. (in the beginning each round was three games no matter what, and the number of games won was your score). Also it would in theory be preferable to have the actual record instead of the score. For a time they listed the record, too, but nowadays it is back to only points. I put a lot of effort into my personal data files to have some background on how players performed (for my interviews, and the occasional statistics article) but even I was not crazy enough to go for the win percentages...
#15

**Comment by mlnmln** [comment]
@OdinFK 
I agree that this is probably VERY hard to achieve, still awesome :)

@czarandy 
I think it should stay in the backlog as a long-term goal. Could we agree on some labels/priorities?

**Comment by czarandy** [comment]
Ok so I added both of you as collaborators. Now you can edit the labels and assign issues and whatnot :).

**Comment by OdinFK** [comment]
I just noticed, that final standings as Wizards shows them include match points these days. Could one of you adjust the crawler that fetches the results from the PT page in such a way that it includes the match points of each player?

It should automatically include match points as "points", and set "played" to 16 for all players that have 12 or more points, and 8 for all other players.

In the best case it would set "played" to 17 for QFs, 18 for SFs, 19 for both finalists, and add a stat "top8wins" with the according number.

This way we can lay the foundation to have win percentages in the future. Of course add some point we would have to go backwards, but this would be a great start.

**Comment by mtgmagicalhack** [comment]
I'm going to update the parser.

**Comment by mtgmagicalhack** [comment]
The parser now also includes match points. 
https://github.com/mtgmagicalhack/mtg-standings-parser

I believe data conversion should be handled within this project.

**Comment by mtgmagicalhack** [comment]
@czarandy @OdinFK Any thoughts? Should we try to pursue this or close it?

**Comment by OdinFK** [comment]
This is cool, but I don't think we should get sidetracked by stuff like this right now. I am very happy that you are back on board, and I would rather you fix some things, that actually need fixing, or add content from my backlog to the website.

Once that is done we can reevaluate what to do next.
