### ISSUE TITLE
Update package versions

### ISSUE THREAD

**Issue by czarandy** [czarandy/mtgptresults#48]
Right now we have some pretty old versions of grunt, react, etc. We should consider updating those but we'll need to watch out for any incompatibilities.

**Comment by czarandy** [comment]
I updated the versions of all the dev packages. The prod packages are harder because we actually have to change some of the code since the react router apis have changed quite a bit. So it's probably best to just leave it as is for now.

**Comment by czarandy** [comment]
I also switched to using babel for the jsx transform + eslint for the linting. You will need to 'npm install' to get the build to work. If you have any problems with conflicting packages, try removing all the old ones first, something like this should work:
cd node_modules
npm uninstall *
npm install

**Comment by mlnmln** [comment]
> I also switched to using babel for the jsx transform + eslint for the linting

I like it. 👍 

Updating worked flawlessly for me after I uninstalled all old packages as you described.

**Comment by czarandy** [comment]
I upgraded everything to the latest versions. This required some code changes since react-router changed substantially but I believe it's working now. https://github.com/czarandy/mtgptresults/commit/8dcf77850d45db5eda5588719dd200a4ebd632ec
