### ISSUE TITLE
Add disqualified players

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#55]
Do we want to list DQed players? Wizards eliminates them from the final standings, but I think they belong in there as they participated in the tournament at least for some time. I could just add them. The problem however is that they should not be ranked.

Do you think we should have them?

I don't think implementing this would be much work. I would add a line

`"rank": "DQ` to the .sjon files.

If 'rank' is set, the tournament file shows the string value of 'rank' instead of the number that would go there. Having such an implementation would also allows us to show the remaining participants of PT 1-3. They would be entered and flagged as PT (participated) or something of that sorts.

**Comment by czarandy** [comment]
Sure, go ahead :)

**Comment by czarandy** [comment]
I'll update the display code once you add the DQed players

**Comment by mlnmln** [comment]
I think this topic is kind of delicate and we need to be 1000% sure that the information about the affected players is correct. 

I'd rather not have it in the site for now. But If both of want it and think it is important, I can live with that.

**Comment by OdinFK** [comment]
I agree, that this should not be handled lightly. A player suspiciously missing from the final standings might not be good enough. However, in many cases there is this

http://magic.wizards.com/en/articles/archive/event-coverage/worlds-2009-round-6-disqualification-2009-11-19
http://magic.wizards.com/en/events/coverage/ptdtk/player-disqualified-pro-tour-dragons-tarkir-2015-04-11
http://magic.wizards.com/en/events/coverage/ptdtk/player-disqualified-ptdtk

I think it should be okay to add the player in these cases.

**Comment by OdinFK** [comment]
@czarandy Could you add the missing players from PT 1-3 and tag them `"rank": "P"` ? I assume you have a more of efficient means of doing that than me (adding them all in manually). I would afterwards check the data for consistency.

@mlnmln Is it okay for you to add DQed players in cases where Wizards mentioned the DQ in the coverage? The likelihood of an error is very close to zero this way. Or do you have other concerns? If you read about these DQs in almost all cases there absolute douchebag moves or worse involved, and it is not exactly like we are trying to undermine somebody's reputation by spreading lies anyway.

**Comment by mlnmln** [comment]
@OdinFK 

I'm all for calling out cheaters. Pretending they never participated like WOTC does in their standings is certainly not the right thing to do. 

I just wonder if this information adds any value to the site. Or lets the affected users stand out too much in the results in comparison to the others. If we'd just display them at the bottom of the standings as "unranked" I'd be fine with that. That way we can adjust their number of participated PTs without giving them too much focus. 

In the end I'm trying to be as non-blocking as possible on this project and won't lose any sleep over this particular issue, just had some concerns. 

If we have an official WOTC statement about the DQ I'm fine with adding them.

**Comment by mlnmln** [comment]
@czarandy DQs are not shown in the tournaments of a player, e.g. http://www.mtgptresults.com/player/jeremy-dezani 

Is that intentional?

**Comment by czarandy** [comment]
Ah yes it was incorrectly showing the numeric index for those. I have fixed it now.

**Comment by czarandy** [comment]
Ok I've added the unranked players from the first three PTs. One interesting consequence is that PVDDR now has the lead in T8/Total :). @OdinFK Let me know if I need to do anything else here

**Comment by czarandy** [comment]
I think this is done after #59 ?
