### ISSUE TITLE
Improve player rankings table

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#56]
> - We have a slight jump in the column width as the sorting icon gets added and removed.
> - Numbers should be right-aligned so it is easier to compare digits.
> - At mobile we could have a fixed table header and first column, also the labels could be shortened.
> 
> I could do these optimisations mid- to end-of-week, as I'm currently down with the flu.
#39

**Comment by mtgmagicalhack** [comment]
@czarandy @OdinFK 

Ok currently pondering. 

We basically can take 2 routes here. 

1. 

Linearize tables on mobile. Left align labels. I did some work a local branch. 
https://github.com/mtgmagicalhack/mtgptresults/tree/responsive-tables
See attachments how it is going to look. 

<img width="367" alt="screen shot 2016-05-28 at 14 03 59" src="https://cloud.githubusercontent.com/assets/19599753/15627249/6bb85f14-24de-11e6-91c3-33e16efc63de.png">
<img width="366" alt="screen shot 2016-05-28 at 14 04 06" src="https://cloud.githubusercontent.com/assets/19599753/15627250/6c084204-24de-11e6-8b5a-a7b8c4a6a037.png">

This looks good, but information density might suffer. 

2. 

Add bootstrap responsive table wrapper
http://getbootstrap.com/css/#tables-responsive
This basically just clips table at device width and allows for horizontal scrolling. 

This doesn't look good, but is very easy to implement. 

<img width="390" alt="screen shot 2016-05-28 at 14 18 27" src="https://cloud.githubusercontent.com/assets/19599753/15627274/1dda0ee0-24df-11e6-83db-67c7c404a9e5.png">
<img width="364" alt="screen shot 2016-05-28 at 14 19 05" src="https://cloud.githubusercontent.com/assets/19599753/15627275/2d72c7e8-24df-11e6-86e2-cd0d8bd8c6b9.png">

Before I invest any more time I'd rather get some feedback from you guys which direction we should be heading.

**Comment by czarandy** [comment]
What if we do option 2 but we fixed the player name so it's always visible as you scroll?

**Comment by mtgmagicalhack** [comment]
> What if we do option 2 but we fixed the player name so it's always visible as you scroll?

I like this idea in general, but the player field is always going to be the widest. This wouldn't leave much space for scrolling. How about we'd just fix the rank column?

**Comment by czarandy** [comment]
We can just set it to a smaller width so the player names wrap to multiple lines. I think it's better this way so that when you scroll right you can tell who actually has the given value.

**Comment by mlnmln** [comment]
👍 I'll try that!

**Comment by mtgmagicalhack** [comment]
👍 I'll try that!

**Comment by OdinFK** [comment]
Looks pretty good right now. Maybe make the player names always visible as czarandy suggests. On a related note, does it make sense to keep the table header always visible? It's relatively obvious which column is for what, so it might not be necessary, but generally I like to always see which is what. Would also make sense for the non-mobile version.

**Comment by mtgmagicalhack** [comment]
I did some more research. Almost every UI library I look at had a dependency to a higher react version. I think we should resolve the prod packages of #48 first. Other than that https://facebook.github.io/fixed-data-table/ looks promising for out tables.

**Comment by czarandy** [comment]
FixedDataTable is ok but it has some issues (e.g., scrolling with arrow keys doesn't work). I think this one is maybe better: https://github.com/bvaughn/react-virtualized

Though both of those require knowing row heights, which can be awkward with variable player name lengths

**Comment by mtgmagicalhack** [comment]
@czarandy @OdinFK Looking back at this, I think the react-virtualised solution in my PR (https://github.com/czarandy/mtgptresults/pull/108) adds to much complexity. I'd suggest using bootstrap responsive tables. It's better than what we currently have for mobile and is almost effortless.
