### ISSUE TITLE
Update twitter profile description

### ISSUE THREAD

**Issue by mlnmln** [czarandy/mtgptresults#58]
> Updates from mtgptresults.com. Also, send us links to your PT tournament reports, and we will them!

There are some words missing. Should be 'include' them. I would also add a line that people should tweet as errors or additions. Would do it on my own, but I somehow can't edit the profile via tweetdeck.

**Comment by OdinFK** [comment]
Apparently only the owner can change the profile. Added the missing 'include' and added the line about tweeting error.s
