### ISSUE TITLE
Improve player view on mobile

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#66]
@mtgmagicalhack You have done a wonderful job in making the frontpage mobile friendly, and the way individual tournaments are displayed is good, too (also your work?). Do you think you could give the individual player view a similar treatment?

**Comment by mtgmagicalhack** [comment]
Sure thing. Will do. 

However, I have to do some thinking before I can come up with st better for tabular data.

**Comment by mtgmagicalhack** [comment]
@OdinFK @czarandy This is fixed as far as I'm concerned.
