### ISSUE TITLE
Nationality

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#74]
Adding nationalities to the metadata file is quite easy manually (also slow, but it works). What format do we want to use for that, though? Do we write the name of the country out in full, or do we use 3 letter country codes? (2 letter is theoretically possible, but 3 is more common and more legible)

I'd prefer using country codes as it will probably lead to more consistency. The country code can be displayed on the website and if we want to switch to full country name on the website at some point, it is probably easy to inlcude some code that translates the country code to full country names.

**Comment by czarandy** [comment]
Sure, we can use the 3 letter codes: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

**Comment by OdinFK** [comment]
Wizards mostly uses the standard codes. For the UK however they use the FIFA codes
NIR = Northern Ireland, WAL = Wales, SCO = Scotland, ENG = England
We have to keep that in mind when we converting country codes to country names.

There are also some obselete codes like SCG (Serbia and Montenegro) but I try to replace these with adequate country codes, so there should not be any of these in the players.json.

**Comment by OdinFK** [comment]
We have nationalities for almost all top players now, and maybe 40% of the rest. I think that should be sufficient to add nationalities to the player info boxes.

The next step after that would be to make the nationality link to a site with the top players of that country.

**Comment by czarandy** [comment]
I added the nationality & hof status to the player pages: http://www.mtgptresults.com/player/jon-finkel

**Comment by OdinFK** [comment]
That's awesome!
Could you put the hof status into the player rankings as well? Either by giving their text a different color or by adding a background color. (I still don't think tags work as well here) I am asking because I think it can be only days (a few weeks at most) until the Hall of Fame ballots will be sent out, and the site will be way more helpful if it provides a good overview over stats of Hall of Famers and non-Hall of Famers.

**Comment by czarandy** [comment]
I colored the hof players in the rankings red.

**Comment by OdinFK** [comment]
I wonder if it we should have flag symbols for the players on the Pro Tour pages? (either before or right after the player name) Not exactly sure about this. What do you think?

**Comment by czarandy** [comment]
That seems cool. Do you know of a place to get all the flag images?

**Comment by mtgmagicalhack** [comment]
+1

https://github.com/lipis/flag-icon-css

**Comment by czarandy** [comment]
@OdinFK I noticed some of the nationalities you added are not valid codes. For example: SCO, ENG, WAL, NIR, DIN. 

I am using the ISO list: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

**Comment by OdinFK** [comment]
I know. DIN sounds like a mistake, but the other ones are the FIFA codes for the UK. Wizards uses them, too. We could also just use GBR for all of them, but then the user would not see for which country the person would play in the WMC.

**Comment by czarandy** [comment]
Oh, I see. I can manually add them as countries.

**Comment by czarandy** [comment]
http://www.mtgptresults.com/tournament/pro-tour-shadows-over-innistrad-2016

**Comment by OdinFK** [comment]
Cool! Maybe flag before the name would look more orderly, though?

**Comment by OdinFK** [comment]
Perfect!!

**Comment by czarandy** [comment]
I changed it to have the flag first and I fixed a couple nationality typos and added the UK codes.

**Comment by czarandy** [comment]
Shall I also add country to the main page and the rankings page?

**Comment by OdinFK** [comment]
I'm not sure. Leaning towards yes on the main page and no for the rankings. What do you think?

**Comment by mtgmagicalhack** [comment]
Great work everyone, thanks! Really adds value to site.

**Comment by OdinFK** [comment]
Where did you get the country flags that we are using? Maybe I could look around for the missing flags?

**Comment by czarandy** [comment]
I got them from this: https://github.com/lipis/flag-icon-css

**Comment by OdinFK** [comment]
From what I get that repository has flags for Scotland/Northern Ireland/Wales/England. The country codes seem to be SCT/NIR/WLS/ENG.

Should I change the code I use for Scotland and Wales? And do you know why England and Northern Ireland flags are not displayed if we are using the right code?

**Comment by czarandy** [comment]
Oh yeah I will fix that.

**Comment by czarandy** [comment]
should be fixed now

**Comment by OdinFK** [comment]
Yes, it works nicely. Thanks!

**Comment by OdinFK** [comment]
Is this actually still open? Looks like you implemented flag display/country code etc.
