### ISSUE TITLE
Parser and apostrophes

### ISSUE THREAD

**Issue by OdinFK** [czarandy/mtgptresults#91]
Our parser always gets irritated by apostrophes. For example "Iyanaga, Jun'ya" in the standings will become "Jun Iyanaga" / jun-iyanaga. Is one of you able to improve this?

**Comment by OdinFK** [comment]
Same problem exists for periods btw. 'Lucy, J. Sawyer' becomes 'J. Lucy'

**Comment by czarandy** [comment]
Do you mean for previous data or for new data we are parsing? @mtgmagicalhack has the latest parsing code so hopefully it doesn't have that problem going forward.

**Comment by OdinFK** [comment]
I must admit that I don't really know, but I always come across these incorrect names. We can wait for PT Eldritch Moon and see if that problem persists, or maybe @mtgmagicalhack knows.

**Comment by czarandy** [comment]
Did you find them in PTSOI?

**Comment by OdinFK** [comment]
I couldn't really say, because it's been quite a while since I worked on that file. However, there are no players with a period or an apostroph in their name in that PT anyway.

**Comment by czarandy** [comment]
Ok let's see if it comes up going forward. The older data I gathered with some older parsing code I had that was definitely not the best ;). Hopefully the new code doesn't have this problem.
